/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SETxF */

#ifndef _Included_SETxF
#define _Included_SETxF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SETxF
 * Method:    SETCF
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SETxF_SETCF
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
